### ISSUE TITLE
Need to include a few more modules in the base install - see comments

### ISSUE THREAD

**Issue by needlestack** [rachelproject/rachelpiOS#10]

**Comment by j-schwartz** [comment]
Actually, for multi-lingual search support I wanted to know if it's hard to add another php module to the build process. You'd have to do the following:

```
apt-get install php-pear
apt-get install php5-dev
pecl install stem
```

There's a few times you have to hit enter in there. And then, as it states at the end of the install, you have to add the following line:

extension=stem.so

To the following files:

/etc/php5/cli/php.ini
/etc/php5/apache2/php.ini

I don't know if it matters, but I add it right above the following lines:

;;;;;;;;;;;;;;;;;;;
; Module Settings ;
;;;;;;;;;;;;;;;;;;;

**Comment by needlestack** [comment]
This is has been added (and tested) to installer.py
