### ISSUE TITLE
Script Failure on Attempt 1

### ISSUE THREAD

**Issue by j-schwartz** [rachelproject/rachelpiOS#12]
![image](https://cloud.githubusercontent.com/assets/9270388/13478500/297fb288-e086-11e5-9a34-11e22bbc8c02.png)

The above image is the last messages I received while running the script on a clean Jessie install.  Upon reboot, RACHEL was not yet installed.  Further diagnostics coming

**Comment by needlestack** [comment]
Script worked on subsequent try for me - for now I'm going to close this as a network error / random crash - will see how common it is as I repeat the build process several times over the next few weeks.
