### ISSUE TITLE
rachelpiOS versioning of script

### ISSUE THREAD

**Issue by j-schwartz** [rachelproject/rachelpiOS#13]
We're going to add to content shell a versioning page that lists all meaningful versions for Raspbian, the install process, and all content sets.  One piece of this, the install process, will require us to date stamp somewhere the script as edits are made.  @spatiald does this for rachelplusOS fairly effectively (ie, current version is v.20160210.0552)

**Comment by needlestack** [comment]
Started using git tags - I will use the same style as Sam - date based in the format: vYYYYMMDD. I have tagged the latest working version of rachelpiOS tag.

For the curious - on your local copy:

`git tag v20160319`

Then when you push:

git push --tags

And that makes it a "release"
