### ISSUE TITLE
Web based safe shutdown

### ISSUE THREAD

**Issue by j-schwartz** [rachelproject/rachelpiOS#14]
https://www.element14.com/community/community/raspberry-pi/raspberrypi_projects/blog/2014/04/02/pi-webpage-reboot

**Comment by j-schwartz** [comment]
A very cool alternative idea: 

https://matthew.mceachen.us/blog/give-your-raspberry-pi-a-shutdown-switch-for-free-1397.html

**Comment by needlestack** [comment]
I have added a "Shutdown" button to the admin page in [contentshell](https://github.com/rachelproject/contentshell). This works through a change to sudoers that gives the www-data user permission to issue /sbin/shutdown.

The change to /etc/sudoers is done in rachelpiOS's installer.py
