### ISSUE TITLE
Script Error: Unable to upgrade Raspbian

### ISSUE THREAD

**Issue by j-schwartz** [rachelproject/rachelpiOS#17]
Started with a clean Jessie install.  Ran raspi-config and received the following error on two different tries.

![image](https://cloud.githubusercontent.com/assets/9270388/14029828/9b4b76ee-f1c1-11e5-92ec-706a33535154.png)

**Comment by needlestack** [comment]
Just tried this just now and it went through alright. Are you using any new hardware (differen SD card, new wifi dongle, etc?) If not, could be there was a broken package hosted on the raspbian update server for a while? Try it again and let me know if it is still happening.

**Comment by mattneel** [comment]
Try:
`sudo apt-get update -y && sudo apt-get dist-upgrade -y`

Run raspi-config again afterwards.

**Comment by j-schwartz** [comment]
I'll try @mattneel 's fix later, but I just ran the script starting with the 3/18 release of Raspbian and it ran fine.  Nice work guys.

**Comment by mattneel** [comment]
The error you were getting is because apt was installing packages in the wrong order. Usually apt-get update will fix it. Also I've got an RPi3 on the way, should be interesting getting everything going on the integrated wifi.

**Comment by needlestack** [comment]
Seems like a temporary issue - closing.
