### ISSUE TITLE
Default user names and passwords

### ISSUE THREAD

**Issue by j-schwartz** [rachelproject/rachelpiOS#19]
Are these listed anywhere?  Trying to log in to KA-Lite and having trouble discovering the default here

**Comment by mattneel** [comment]
https://github.com/rachelproject/rachelpiOS/blob/master/installer.py#L21 is where the KA-Lite user name and password are set in the script.

Should be rachel/rachel.

**Comment by j-schwartz** [comment]
Many thanks
