### ISSUE TITLE
more dependencies for _h5ai

### ISSUE THREAD

**Issue by needlestack** [rachelproject/rachelpiOS#24]
The h5ai thumbnail previews require a few extra packages:
- `apt-get install php5-gd` - for image thumbs
- `apt-get install imagemagick` - for pdf thumbs
- `apt-get install libav-tools` - for movie thumbs
- `apt-get install zip` - for... zip thumbs?
- `chmod 777 /var/www/_h5ai/cache`

**Comment by needlestack** [comment]
Worth noting that the thumb creation process can be pretty slow as they browse around. Ideally one should pre-build the thumbnail cache. But wget doesn't seem to work because it doesn't speak javascript.

**Comment by needlestack** [comment]
For performance reasons, we're moving away from _h5ai - all modules should have a pre-build html index and the file-upload module needs something more lightweight.

**Comment by j-schwartz** [comment]
totally agreed, we should remove it from the build entirely.
