### ISSUE TITLE
Unable to access "Soluciones Prácticas" module Rachel ES 3.0

### ISSUE THREAD

**Issue by pedroagont** [rachelproject/rachelpiOS#29]
Everytime you hit "Soluciones Prácticas" module, it gets you to this link with a Not Found screen:

`http://192.168.1.210/modules/soluciones_es/soluciones/index.html
`

So instead you need to change part of "index.htmlf" at "/var/www/modules/soluciones_es" the same as this:

```
<a href="<?php echo $dir ?>/index.html">   #CHANGE URL FROM /soluciones/index.html TO /index.html
<img src="<?php echo $dir ?>/logo.png" alt="">
</a>

<!-- Title and link to your module's index.html - same as above. -->
<h2><a href="<?php echo $dir ?>/index.html">Soluciones Pr&aacute;cticas</a></h2>  #SAME AS ABOVE
```

**Comment by needlestack** [comment]
Thanks for the report! I have fixed this in both the raspberry pi image and the module repository.
