### ISSUE TITLE
Access the admin page

### ISSUE THREAD

**Issue by wegunterjr** [rachelproject/rachelpiOS#31]
how do you get to the admin page when installing the rachel os on the pi with the https://github.com/rachelproject/rachelpiOS instructions.   It is installled, I can access the pi with the ssh as expected, i can see the main web page, but i cannot see any admin page.

**Comment by needlestack** [comment]
The admin link should be showing near the top right corner of the RACHEL front page. When you click the link, you'll need to log in with the username "admin" and the password "rachel". Our current default passwords are here:

https://github.com/rachelproject/rachelpiOS/wiki/Default-Passwords

But note that the RACHEL-Pi image uses the older password listed.
