### ISSUE TITLE
Admin login page not working on CHIP

### ISSUE THREAD

**Issue by promiseowolabi** [rachelproject/rachelpiOS#33]
I cloned the repo [https://promiseowolabi@bitbucket.org/promiseowolabi/rachelchip.git](url) and made slight adjustments to install on CHIP. The Admin login page user root/rachel won't login. Please what username/password should we use.

**Comment by promiseowolabi** [comment]
The right repo link - https://bitbucket.org/promiseowolabi/rachelchip

**Comment by needlestack** [comment]
You can find our latest default passwords here:

  https://github.com/rachelproject/rachelpiOS/wiki/Default-Passwords

Also, can you tell me more about the CHIP? If you have a good build we'd love to share it with others!

**Comment by promiseowolabi** [comment]
Thanks for the link, I can login now.
The CHIP is a single board computer like the RPi, developed by NextThingCo https://getchip.com/
I will share the build I have next, it works well as expected.

**Comment by promiseowolabi** [comment]
https://github.com/promiseowolabi/rachel-chip

**Comment by promiseowolabi** [comment]
I also noticed that the "iptables" are not persistent after rebooting. Made some changes to the /etc/rc.local command.
sudo("sh -c 'echo ifconfig wlan1 10.10.10.10 >> /etc/rc.local; echo service udhcpd restart >> /etc/rc.local; echo **\"iptables-restore < /etc/iptables.ipv4.nat\" >> /etc/rc.local**'") or die("Unable to setup udhcpd reset at boot.")
