### ISSUE TITLE
Add Kiwix to Default Installation Script

### ISSUE THREAD

**Issue by j-schwartz** [rachelproject/rachelpiOS#9]
install_kiwix():
    die("KiwiX installation is not yet supported by this installation script.")

**Comment by needlestack** [comment]
Ok, kiwix is now installed as part of the build, along with an init.d script. It will start at boot, and additionally the following should work:

 `service kiwix (start|stop|restart|status)`

Also, the startup script will scan the /var/www/modules directory for zim files and add/remove them from /var/kiwix/library.xml as needed. Whenever a zim module is added or removed, you have to run `service kiwix restart` for it to rescan.

The zim files in the modules directory must in the proper place -- specifically /var/www/modules/[modname]/data/content/[zimfilename] -- but this is only a concern when creating the modules originally.
